topo_relations:
  -
    type: host
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: host
  -
    type: container
    dependingitems:
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: container
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: proc
    dependingitems:
      -
        id: runs_on
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
            requires:
              -
                side: from
                label: container_id
                value: null
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: appinstance
            matches:
              -
                from: pgid
                to: pgid
              -
                from: machine_id
                to: machine_id
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: container
            matches:
              -
                from: tgid
                to: proc_id
              -
                from: machine_id
                to: machine_id
      -
        id: connect
        layer: indirect
        toTypes:
          -
            type: proc
  -
    type: thread
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: endpoint
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: tcp_link
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
      -
        id: is_peer
        layer: direct
        toTypes:
          -
            type: tcp_link
            matches:
              -
                from: server_ip
                to: server_ip
              -
                from: server_port
                to: server_port
              -
                from: client_ip
                to: client_ip
              -
                from: client_port
                to: client_port
            conflicts:
              -
                from: role
                to: role
  -
    type: sli
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: proc
            matches:
              -
                from: tgid
                to: tgid
              -
                from: machine_id
                to: machine_id
  -
    type: cpu
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: nic
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: disk
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: host
            matches:
              -
                from: machine_id
                to: machine_id
  -
    type: block
    dependingitems:
      -
        id: belongs_to
        layer: direct
        toTypes:
          -
            type: disk
            matches:
              -
                from: disk_name
                to: disk_name
              -
                from: machine_id
                to: machine_id
